<a href="https://colab.research.google.com/github/JenFaith/DS-Unit-1-Sprint-1-Data-Wrangling-and-Storytelling/blob/master/Faith%20-%20LS_DS_134_Linear_Algebra_Assignment_ANSWERS_ipynb_txt.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Autograded Notebook (Canvas & CodeGrade)

This notebook will be automatically graded. It is designed to test your answers and award points for the correct answers. Following the instructions for each Task carefully.

### Instructions

* **Download this notebook** as you would any other ipynb file
* **Upload** to Google Colab or work locally (if you have that set-up)
* **Delete `raise NotImplementedError()`**
* Write your code in the `# YOUR CODE HERE` space
* **Execute** the Test cells that contain `assert` statements - these help you check your work (others contain hidden tests that will be checked when you submit through Canvas)
* **Save** your notebook when you are finished
* **Download** as a `ipynb` file (if working in Colab)
* **Upload** your complete notebook to Canvas (there will be additional instructions in Slack and/or Canvas)

# Lambda School Data Science - Unit 1 Sprint 3 Module 4

### Learning Objectives

* define a vector and calculate a vector length and dot product
* define a matrix and calculate a matrix dot product, transpose, and inverse
* explain cosine similarity and compute the similarity between two vectors
* use linear algebra to solve for linear regression coefficients

## Part A: Introduction

### Statistical significance between head size and brain weight in healthy adult humans

The `Brainhead.csv` dataset provides information on 237 individuals who were subject to post-mortem examination at the Middlesex Hospital in London around the turn of the 20th century. Study authors used cadavers to see if a relationship between brain weight and other more easily measured physiological characterizes such as age, sex, and head size could be determined. The end goal was to develop a way to estimate a person’s brain size while they were still alive (as the living aren’t keen on having their brains taken out and weighed).

**We wish to determine if we can improve on our model of the linear relationship between head size and brain weight in healthy human adults.**

Source: R.J. Gladstone (1905). "A Study of the Relations of the Brain to the Size of the Head", Biometrika, Vol. 4, pp105-123.

### Use the above information to complete the following tasks. 

**Task 1** - Load the data

Let's load the data! The URL has been provided as well as the imports for pandas and numpy.

* load your CSV file into a DataFrame named `df`

In [2]:
# Task 1

import pandas as pd
import numpy as np

data_url = 'https://raw.githubusercontent.com/LambdaSchool/data-science-practice-datasets/main/unit_1/Brainhead/Brainhead.csv'

# YOUR CODE HERE
df = pd.read_csv(data_url)

# Print out your DataFrame
df.head()

Gender  Age  Head  Brain
0       1    1  4512   1530
1       1    1  3738   1297
2       1    1  4261   1335
3       1    1  3777   1282
4       1    1  4177   1590

**Task 2**

Store the response variable (brain size) as a matrix called Y.

* import numpy
* assign `Brain` to a matrix variable called `Y`
* print out your matrix to make sure it's correct

In [ ]:
# Task 3

# YOUR CODE HERE
import numpy as np

Y = np.array(df['Brain']).reshape(-1,1)

# Print your matrix
print(Y)

In [5]:
# Task 3 - Test

assert Y.shape == (237, 1), "Is your Y matrix of the correct shape?"


**Task 4**

Store the explanatory variable (head size) as the matrix `X`.  Don't forget to include the column of ones for the intercept term.

* create an array of ones with the name `ones`
* create another array with the name `head`
* combine the two arrays above to create your matrix, and call it `X`

In [17]:
# Task 4

# YOUR CODE HERE
ones = np.repeat(1, len(df)).reshape(-1,1)
head = np.array(df['Head']).reshape(-1,1)

X = np.concatenate((ones, head), axis = 1)

# Print your matrix
print(X)

[[   1 4512]
 [   1 3738]
 [   1 4261]
 [   1 3777]
 [   1 4177]
 [   1 3585]
 [   1 3785]
 [   1 3559]
 [   1 3613]
 [   1 3982]
 [   1 3443]
 [   1 3993]
 [   1 3640]
 [   1 4208]
 [   1 3832]
 [   1 3876]
 [   1 3497]
 [   1 3466]
 [   1 3095]
 [   1 4424]
 [   1 3878]
 [   1 4046]
 [   1 3804]
 [   1 3710]
 [   1 4747]
 [   1 4423]
 [   1 4036]
 [   1 4022]
 [   1 3454]
 [   1 4175]
 [   1 3787]
 [   1 3796]
 [   1 4103]
 [   1 4161]
 [   1 4158]
 [   1 3814]
 [   1 3527]
 [   1 3748]
 [   1 3334]
 [   1 3492]
 [   1 3962]
 [   1 3505]
 [   1 4315]
 [   1 3804]
 [   1 3863]
 [   1 4034]
 [   1 4308]
 [   1 3165]
 [   1 3641]
 [   1 3644]
 [   1 3891]
 [   1 3793]
 [   1 4270]
 [   1 4063]
 [   1 4012]
 [   1 3458]
 [   1 3890]
 [   1 4166]
 [   1 3935]
 [   1 3669]
 [   1 3866]
 [   1 3393]
 [   1 4442]
 [   1 4253]
 [   1 3727]
 [   1 3329]
 [   1 3415]
 [   1 3372]
 [   1 4430]
 [   1 4381]
 [   1 4008]
 [   1 3858]
 [   1 4121]
 [   1 4057]
 [   1 3824]
 [   1 3394]
 [   1 3558]

In [ ]:
# Task 4 - Test

assert ones.shape == (237, 1), "Is your ones matrix of the correct shape?"
assert head.shape == (237, 1), "Is your 'head' matrix of the correct shape?"
assert X.shape == (237, 2), "Is your X matrix of the correct shape?"


**Task 5**

Calculate $X^T$.  Explain what the transpose of a matrix is.

* calculate the transpose of `X` and assign it to the variable `X_T`

Short Answer:


In [ ]:
# Task 5

# YOUR CODE HERE
X_T = np.transpose(X)

# Print your matrix
print(X_T)

In [ ]:
# Task 5 - Test

assert X_T.shape == (2, 237), "Is your X_T matrix of the correct shape?"


**Task 6**

Use matrix multiplication to calculate $X^TX$

* assign the results of your calculation to `X_T_X`

In [20]:
# Task 6

# YOUR CODE HERE
X_T_X = np.matmul(X_T,X)

print(X_T_X)

[[       237     861256]
 [    861256 3161283190]]


In [21]:
# Task 6 - Test

assert X_T_X.shape == (2, 2), "Is your X_T_X matrix of the correct shape?"


**Task 7**

Calculate $(X^TX)^{-1}$.  Explain what the inverse of a matrix is.

* assign your calculation to the variable `X_T_X_inv`

Short Answer: 

In [22]:
# Task 7

# YOUR CODE HERE
X_T_X_inv = np.linalg.inv(X_T_X)

print(X_T_X_inv)

[[ 4.23638519e-01 -1.15415543e-04]
 [-1.15415543e-04  3.17599920e-08]]


In [ ]:
# Task 7 - Test

assert X_T_X_inv.shape == (2, 2), "Is your X_T_X matrix of the correct shape?"


**Task 8**

Use matrix multiplication to calculate $X^TY$.

* assign your result to the variable `X_T_Y`

In [24]:
# Task 8

# YOUR CODE HERE
X_T_Y = np.matmul(X_T, Y)

print(X_T_Y)
X_T_Y.shape

[[    304041]
 [1113176805]]


(2, 1)

In [ ]:
# Task 8 - Test

assert X_T_Y.shape == (2, 1), "Is your X_T_Y matrix of the correct shape?"


**Task 9**

Use the results from your previous tasks to calculate the values of the slope and intercept using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

* assign the results of your calculation to the variable `B`

In [25]:
# Task 9

# YOUR CODE HERE
B = np.matmul(X_T_X_inv, X_T_Y)

print(B)

[[3.25573421e+02]
 [2.63429339e-01]]


In [ ]:
# Task 9 - Test

assert B.shape == (2, 1), "Is your B matrix of the correct shape?"


**Task 10**

Now, we're going to verify our linear algebra calculations by fitting a linear model We'll use the results of the linear model to compare to our calculated values for the slope and intercept.

* import the `statsmodel.formula.api` library and fit an `ols` model (enter the model in the format Y ~ X)
* assign your model to the variable `model`

Compare your `model.params` output to the two values in the `B` matrix you calculated above.

In [37]:
# Task 10

# YOUR CODE HERE
from statsmodels.formula.api import ols
model = ols('Brain ~ Head', data = df).fit()

print(model.params)

Intercept    325.573421
Head           0.263429
dtype: float64


In [ ]:
# Task 10 - Test
# Hidden tests - you will see the results when you submit to Canvas

**Task 11**

Create a new X matrix that includes columns for both head size and age group.

* create an array for head size and assign it to the variable `head`
* create a new variable by subtracting `1` from each value in `df['Age']`; call the new column `Age_01`
* assign the array for age group to the variable `age`
* concatenate the following three arrays and assign to the variable `X`: `ones`, `head`, `age`

In [ ]:
# Task 11

# YOUR CODE HERE
df['Age_01'] = df['Age']-1

age = np.array(df['Age_01']).reshape(-1,1)


X = np.concatenate((ones, head, age), axis = 1)

# Print your results
print(X)

In [ ]:
# Task 11 - Test

assert head.shape == (237, 1), "Is your 'head' matrix of the correct shape?"
assert age.shape == (237, 1), "Is your 'age' matrix of the correct shape?"
assert X.shape == (237, 3), "Is your X matrix of the correct shape?"


**Task 12**

Now, calculate the values of the intercept and slope terms for head size and age using the formula $$ B = (X^{'}X)^{-1}X^{'}Y$$

* break it down into smaller steps, in separate cells if needed
* COMMENT all the steps, so you can troubleshoot if there is a mistake

This task will not be autograded but verify your answers! 

In [55]:
# Task 12
# B = (X'X)^-1 X'Y

# YOUR CODE HERE


#Step 1 X'
X_T = np.transpose(X)
      #print(X_T)

#Step 2 X'X
X_T_X = np.matmul(X_T, X)
#X_T_X

#Step 3 (X'X)-1
X_T_X_inv = np.linalg.inv(X_T_X)

#Step 4
X_T_Y= np.matmul(X_T, Y)

#Step 5
B = np.matmul(X_T_X_inv, X_T_Y)

# Final result!
print(B)

[[ 3.47550501e+02]
 [ 2.60438766e-01]
 [-2.07316446e+01]]


**Task 13**

We're going to fit another OLS model and then confirm our answer with what we calculated for `B` in **Task 12**

* fit an OLS model as you did above but your input will be in the two independent variables head size and age (your model input should be Y ~ X1 + X2)
* assign the model results to the variable `model2`

Compare your `model2.params` to the values you determined for `B` in Task 12 - do they match?

In [56]:
# Task 13

# YOUR CODE HERE

model2 = ols('Brain~Head + Age', data = df).fit()

print(model2.params)

Intercept    368.282145
Head           0.260439
Age          -20.731645
dtype: float64


In [ ]:
# Task 13 - Test
# Hidden tests - you will see the results when you submit to Canvas

## Part B: Cosine Similarity

Use the following information to answer the remaining Tasks in the project.

The song writing collaboration between John Lennon and Paul McCartney was one of the most productive in music history.  Unlike many other partnerships where one individual wrote lyrics and one wrote music, Lennon and McCartney composed both, and it was decided that any song that was written would be credited to both.  In the beginning of their relationship, many of their songs were truly collaborative.  However, later on, they often worked separately with little to no input from the other.    

Because of extensive reporting on the Beatles over the years, it is generally known if a Lennon-McCartney song was a true collaboration, primarily (or totally) written by Lennon, or primarily (or totally) written by McCartney.  

**However, there are several disputed songs where both Lennon and McCartney at times claimed to be the sole (or primary) composer.**

We will now use cosine similarity to determine if *Ticket to Ride* (disputed) is most similar to *From Me to You* (collaborative, not disputed) or *Strawberry Fields* (Lennon, not disputed).

From the Wikipedia article on the Lennon-McCartney Partnership: Lennon said that McCartney's contribution was limited to "the way Ringo played the drums". In Many Years from Now, McCartney said "we sat down and wrote it together ... give him 60 percent of it."

**Task 14**

Import the text of Strawberry Fields and calculate the frequency of song lyrics. The code has been provided for you - run the cell to see the output.

In [58]:
# Task 14
# Strawberry Fields - John Lennon (not disputed)

Strawberry_ = "let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever living is easy with eyes closed misunderstanding all you see its getting hard to be someone but it all works out it doesnt matter much to me let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever no one I think is in my tree I mean it must be high or low that is you cant you know tune in but its all right that is I think its not too bad let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever always no sometimes think but you know I know when it's a dream I think er no I mean er yes but its all wrong that is I think I disagree let me take you down cause Im going to Strawberry Fields nothing is real and nothing to get hung about Strawberry Fields forever Strawberry Fields forever Strawberry Fields forever"
Strawberry_df = pd.DataFrame({"Words": Strawberry_.split()})
Strawberry_df_freq = pd.DataFrame(pd.crosstab(index=Strawberry_df['Words'],columns='count'))

# Uncomment to display
Strawberry_df_freq[0:50]

col_0             count
Words                  
Fields               10
I                     8
Im                    4
Strawberry           10
a                     1
about                 4
all                   4
always                1
and                   4
bad                   1
be                    2
but                   4
cant                  1
cause                 4
closed                1
disagree              1
doesnt                1
down                  4
dream                 1
easy                  1
er                    2
eyes                  1
forever               6
get                   4
getting               1
going                 4
hard                  1
high                  1
hung                  4
in                    2
is                    9
it                    3
it's                  1
its                   4
know                  3
let                   4
living                1
low                   1
matter                1
me                    5
mean                  2
misunderstanding      1
much                  1
must                  1
my                    1
no                    3
not                   1
nothing               8
one                   1
or                    1

**Task 15

Read in the provided text of "From Me to You" and calculate the frequency of words in the song lyrics. The code has been provided for you - run the cell to see the output.

In [59]:
# Task 15
# From Me to You - Lennon and McCartney (not disputed)

Me_ = "if there's anything that you want if there's anything I can do just call on me and Ill send it along with love from me to you Ive got everything that you want like a heart thats oh so true just call on me and Ill send it along with love from me to you Ive got arms that long to hold you and keep you by my side Ive got lips that long to kiss you and keep you satisfied oh if theres anything that you want if theres anything I can do just call on me and Ill send it along with love from me to you from me to you just call on me and Ill send it along with love from me to you Ive got arms that long to hold you and keep you by my side Ive got lips that long to kiss you and keep you satisfied oh if theres anything that you want if theres anything I can do just call on me and Ill send it along with love from me to you to you to you to you"
Me_df = pd.DataFrame({"Words": Me_.split()})
Me_df_freq = pd.DataFrame(pd.crosstab(index=Me_df['Words'],columns='count'))

# Uncomment to display
Me_df_freq[0:50]

col_0       count
Words            
I               3
Ill             5
Ive             5
a               1
along           5
and             9
anything        6
arms            2
by              2
call            5
can             3
do              3
everything      1
from            6
got             5
heart           1
hold            2
if              6
it              5
just            5
keep            4
kiss            2
like            1
lips            2
long            4
love            5
me             11
my              2
oh              3
on              5
satisfied       2
send            5
side            2
so              1
that            8
thats           1
there's         2
theres          4
to             13
true            1
want            4
with            5
you            21

**Task 16**

Read in the provided text of "Ticket to Ride" and calculate the frequency of words in the song lyrics. The code has been provided for you - run the cell to see the output.

In [60]:
# Task 16
# Ticket to Ride (disputed)

Ticket_ = "I think Im gonna be sad I think its today yeah the girl thats driving me mad is going away shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care she said that living with me is bringing her down yeah for she would never be free when I was around shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care I dont know why shes ridin so high she ought to think twice she ought to do right by me before she gets to saying goodbye she ought to think twice she ought to do right by me I think Im gonna be sad I think its today yeah the girl thats driving me mad is going away yeah shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care I dont know why shes ridin so high she ought to think twice she ought to do right by me before she gets to saying goodbye she ought to think twice she ought to do right by me she said that living with me is bringing her down yeah for she would never be free when I was around ah shes got a ticket to ride shes got a ticket to ride shes got a ticket to ride but she dont care my baby dont care my baby dont care my baby dont care my baby dont care my baby dont care my baby dont care"
Ticket_df = pd.DataFrame({"Words": Ticket_.split()})
Ticket_df_freq = pd.DataFrame(pd.crosstab(index=Ticket_df['Words'],columns='count'))

# Uncomment to display
Ticket_df_freq[0:50]

col_0     count
Words          
I             8
Im            2
a            12
ah            1
around        2
away          2
baby          6
be            4
before        2
bringing      2
but           4
by            4
care         10
do            4
dont         12
down          2
driving       2
for           2
free          2
gets          2
girl          2
going         2
gonna         2
goodbye       2
got          12
her           2
high          2
is            4
its           2
know          2
living        2
mad           2
me            8
my            6
never         2
ought         8
ride         12
ridin         2
right         4
sad           2
said          2
saying        2
she          18
shes         14
so            2
that          2
thats         2
the           2
think         8
ticket       12

**Task 17**

Now it's your turn to complete some linear algebra calculations! In this task, we need to concatenate "Ticket to Ride" and "Strawberry Fields" and calculate the cosine similarity. Two linear algebra imports have been provided

* concatenate `Strawberry_df_freq` and `Ticket_df_freq` to create a new DataFrame
* assign your final result to `cos_sim_1`

Hint: you might need to use `.fillna()` on your DataFrame

In [82]:
# Task 17
# Compare 'Strawberry Fields' to 'Ticket to Ride'

# Imports for linear algebra
from numpy import dot
from numpy.linalg import norm


dfs = [Strawberry_df_freq, Ticket_df_freq]
all_words = np.concatenate(dfs, axis = 1)
all_words = all_words.fillna(0)
all_words.columns = ['Strawberry Fields', 'Ticket Ride']

#all_words.head()
cos_sim_1 = dot(all_words['Strawberry Fields'], all_words['Ticket Ride']) /(norm(all_words['Strawberry Fields'])*norm(all_words['Ticket Ride']))



# Print out your result
print(cos_sim_1)

0.324035859004908


In [ ]:
# Task 17 - Test
# Hidden tests - you will see the results when you submit to Canvas

**Task 18**

Now, we'll compare "Ticket to Ride" and "From Me to You" and calculate the cosine similarity.

* concatenate `Ticket_df_freq` and `Me_df_freq` to create a new DataFrame
* assign your final result to `cos_sim_2`

Hint: you might need to use `.fillna()` on your DataFrame

In [88]:
# Taek 18
# Compare From Me to You to Ticket to Ride

# YOUR CODE HERE

dfs_2 = [Ticket_df_freq, Me_df_freq]
all_words2 = pd.concat(dfs_2, axis=1)
all_words2 = all_words2.fillna(0)
all_words2.columns = ['Ticket Ride', 'From Me to You']

#all_words.head()
cos_sim_2 = dot(all_words2['Ticket Ride'], all_words2['From Me to You']) /(norm(all_words2['Ticket Ride'])*norm(all_words2['From Me to You']))


# Print out your result
print(cos_sim_2)

0.2882268853551227


In [ ]:
# Task 18 - Test
# Hidden tests - you will see the results when you submit to Canvas

**Summary**

What is your conclusion about "Ticket to Ride"?  Does it appear most similar to "Strawberry Fields" (Lennon) or "From Me to You" (collaborative)?

ANSWER:

Appears most similar to "Strawberry Fields" (Lennon)